name: Deploy Angular to S3

# Rulează la push pe develop sau manual
on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Angular
        run: npm run build -- --configuration=production

      - name: Sync to S3
        uses: aws-actions/s3-sync@v2
        with:
          source-dir: dist/angular-cognito/browser
          dest-dir: /
          bucket: ${{ secrets.S3_BUCKET_NAME }}
          region: ${{ secrets.AWS_REGION }}
          delete: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
